### ISSUE TITLE
GetAvailablePlayers doesn't detect on macOS

### ISSUE THREAD

**Issue by rjgarciam** [fcinema/desktop-app#1]
GetAvailablePlayers only displays ffplay and file on OS X (10.10.5). Installed VLC version is 2.2.4 in its default path.

**Comment by arrietaeguren** [comment]
Try running "which vlc" in the command line. Looks like VLC must be in you PATH for the "which" npm module to work. We will have to try another approach if it is not in the PATH by default.

**Comment by rjgarciam** [comment]
'which vlc' returns 'not found'. It seems that OS X apps are not added to the path by default, but they can be launched from command line through 'Launch Services' database. More info: http://superuser.com/questions/521590/osx-using-cli-version-of-vlc
