### ISSUE TITLE
Add support for HTML5 (Netflix, Youtube...)

### ISSUE THREAD

**Issue by arrietaeguren** [fcinema/desktop-app#5]
1. load any url in webview (ricardo's job)
2. search film by url (must create an api endpoint for network streams)
3. select scenes (must think how to sync, good side is that netflix probably streams always the same version)
4. play 
  + `var video = document.getElementsByTagName("video")[0]`
  + get time `var time = video.currentTime`
  + set time `video.currentTime = 500`

**Comment by arrietaeguren** [comment]
`video.currentTime = 500` crash on Netflix
Two options
1) http://stackoverflow.com/questions/27927950/controlling-netflix-html5-playback-with-tampermonkey-javascript. Mainly the https://www.stephanboyer.com/post/105/netflix-party-synchronize-netflix-video-playback bit. Problems with this approach: seek is not accurate, seek bar is visible. Hard to implement. Need testing
2) Hide video and mute sound. Problems. You notice something is going on. We can put some text to distract the user. Tested, works like charm!
`video.style.display = "none";
video.muted = true;`

**Comment by arrietaeguren** [comment]
On Amazon Video both: `get time var time = video.currentTime` and `set time video.currentTime = 500` work :). Jumps are very smooth. Crash (need to press pause and play again) if we jump too much (more than 5s) guess it is because of the buffering.

**Comment by arrietaeguren** [comment]
In order to sync, this might be helpful https://github.com/JamesKyburz/electron-screenshot/blob/master/index.js

**Comment by maxstoller** [comment]
Hi @arrietaeguren, I tried syncing with the 2nd option your above comment, but Netflix is still crashing. Have you figured out a way around this?

```
var video = $('video')[0];
video.style.display = 'none';
video.muted = true;
video.currentTime = 500;
```

**Comment by arrietaeguren** [comment]
Hi Max, I haven't found a good workaround yet. The second option is a "mute", "hide" and "fast-forward" approach, so just set
```
video.style.visibility = 'hidden';
video.muted = true;
video.playbackRate = 16;
```
and set back to normal when you reach the objective time. The result is okay if you are just skipping a few seconds, a bit of a pain if you are skipping several minutes.

There is probably a better workaround, but I'm not aware of it. Please let me know if you find anything better, I'll keep you updated too

**Comment by maxstoller** [comment]
@arrietaeguren Gotcha, thanks. Not sure there's a great solution, but will let you know if something comes up. :)
